version: '3'

tasks:
  sources:
    aliases: [src]
    cmds:
      - cmd: go run github.com/jmattheis/goverter/cmd/goverter gen -global 'skipCopySameType yes' ./...
      - cmd: go fmt ./...
      - cmd: go build ./...

  tests:
    aliases: [test]
    cmds:
      - cmd: go test ./...
